export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar', country: 'us' },
  { code: 'EUR', name: 'Euro', country: 'eu' },
  { code: 'GBP', name: 'British Pound', country: 'gb' },
  { code: 'INR', name: 'Indian Rupee', country: 'in' },
  { code: 'AUD', name: 'Australian Dollar', country: 'au' },
  { code: 'CAD', name: 'Canadian Dollar', country: 'ca' },
  { code: 'JPY', name: 'Japanese Yen', country: 'jp' },
  { code: 'CNY', name: 'Chinese Yuan', country: 'cn' },
  { code: 'SGD', name: 'Singapore Dollar', country: 'sg' },
  { code: 'CHF', name: 'Swiss Franc', country: 'ch' },
  { code: 'HKD', name: 'Hong Kong Dollar', country: 'hk' },
  { code: 'NZD', name: 'New Zealand Dollar', country: 'nz' },
  { code: 'KRW', name: 'South Korean Won', country: 'kr' },
  { code: 'MXN', name: 'Mexican Peso', country: 'mx' },
  { code: 'BRL', name: 'Brazilian Real', country: 'br' },
  { code: 'ZAR', name: 'South African Rand', country: 'za' },
  { code: 'RUB', name: 'Russian Ruble', country: 'ru' },
  { code: 'NOK', name: 'Norwegian Krone', country: 'no' },
  { code: 'SEK', name: 'Swedish Krona', country: 'se' },
  { code: 'TRY', name: 'Turkish Lira', country: 'tr' },
  { code: 'AED', name: 'United Arab Emirates Dirham', country: 'ae' },
  { code: 'SAR', name: 'Saudi Riyal', country: 'sa' },
  { code: 'THB', name: 'Thai Baht', country: 'th' },
  { code: 'IDR', name: 'Indonesian Rupiah', country: 'id' },
  { code: 'MYR', name: 'Malaysian Ringgit', country: 'my' },
  { code: 'PHP', name: 'Philippine Peso', country: 'ph' },
  { code: 'VND', name: 'Vietnamese Dong', country: 'vn' },
  { code: 'EGP', name: 'Egyptian Pound', country: 'eg' },
  { code: 'NGN', name: 'Nigerian Naira', country: 'ng' },
  { code: 'KES', name: 'Kenyan Shilling', country: 'ke' },
  { code: 'ARS', name: 'Argentine Peso', country: 'ar' },
  { code: 'COP', name: 'Colombian Peso', country: 'co' },
  { code: 'CLP', name: 'Chilean Peso', country: 'cl' },
  { code: 'PEN', name: 'Peruvian Sol', country: 'pe' },
  { code: 'DKK', name: 'Danish Krone', country: 'dk' },
  { code: 'PLN', name: 'Polish Zloty', country: 'pl' },
  { code: 'ILS', name: 'Israeli New Shekel', country: 'il' },
  { code: 'PKR', name: 'Pakistani Rupee', country: 'pk' },
  { code: 'BDT', name: 'Bangladeshi Taka', country: 'bd' },
];

export const getFlagUrl = (countryCode) => {
  return `https://flagcdn.com/w40/${countryCode.toLowerCase()}.png`;
};
