export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar', country: 'us', countryName: 'United States' },
  { code: 'EUR', name: 'Euro', country: 'eu', countryName: 'European Union' },
  { code: 'GBP', name: 'British Pound', country: 'gb', countryName: 'United Kingdom' },
  { code: 'INR', name: 'Indian Rupee', country: 'in', countryName: 'India' },
  { code: 'AUD', name: 'Australian Dollar', country: 'au', countryName: 'Australia' },
  { code: 'CAD', name: 'Canadian Dollar', country: 'ca', countryName: 'Canada' },
  { code: 'JPY', name: 'Japanese Yen', country: 'jp', countryName: 'Japan' },
  { code: 'CNY', name: 'Chinese Yuan', country: 'cn', countryName: 'China' },
  { code: 'SGD', name: 'Singapore Dollar', country: 'sg', countryName: 'Singapore' },
  { code: 'CHF', name: 'Swiss Franc', country: 'ch', countryName: 'Switzerland' },
  { code: 'HKD', name: 'Hong Kong Dollar', country: 'hk', countryName: 'Hong Kong' },
  { code: 'NZD', name: 'New Zealand Dollar', country: 'nz', countryName: 'New Zealand' },
  { code: 'KRW', name: 'South Korean Won', country: 'kr', countryName: 'South Korea' },
  { code: 'MXN', name: 'Mexican Peso', country: 'mx', countryName: 'Mexico' },
  { code: 'BRL', name: 'Brazilian Real', country: 'br', countryName: 'Brazil' },
  { code: 'ZAR', name: 'South African Rand', country: 'za', countryName: 'South Africa' },
  { code: 'RUB', name: 'Russian Ruble', country: 'ru', countryName: 'Russia' },
  { code: 'NOK', name: 'Norwegian Krone', country: 'no', countryName: 'Norway' },
  { code: 'SEK', name: 'Swedish Krona', country: 'se', countryName: 'Sweden' },
  { code: 'TRY', name: 'Turkish Lira', country: 'tr', countryName: 'Turkey' },
  { code: 'AED', name: 'United Arab Emirates Dirham', country: 'ae', countryName: 'United Arab Emirates, Dubai' },
  { code: 'SAR', name: 'Saudi Riyal', country: 'sa', countryName: 'Saudi Arabia' },
  { code: 'THB', name: 'Thai Baht', country: 'th', countryName: 'Thailand' },
  { code: 'IDR', name: 'Indonesian Rupiah', country: 'id', countryName: 'Indonesia' },
  { code: 'MYR', name: 'Malaysian Ringgit', country: 'my', countryName: 'Malaysia' },
  { code: 'PHP', name: 'Philippine Peso', country: 'ph', countryName: 'Philippines' },
  { code: 'VND', name: 'Vietnamese Dong', country: 'vn', countryName: 'Vietnam' },
  { code: 'EGP', name: 'Egyptian Pound', country: 'eg', countryName: 'Egypt' },
  { code: 'NGN', name: 'Nigerian Naira', country: 'ng', countryName: 'Nigeria' },
  { code: 'KES', name: 'Kenyan Shilling', country: 'ke', countryName: 'Kenya' },
  { code: 'ARS', name: 'Argentine Peso', country: 'ar', countryName: 'Argentina' },
  { code: 'COP', name: 'Colombian Peso', country: 'co', countryName: 'Colombia' },
  { code: 'CLP', name: 'Chilean Peso', country: 'cl', countryName: 'Chile' },
  { code: 'PEN', name: 'Peruvian Sol', country: 'pe', countryName: 'Peru' },
  { code: 'DKK', name: 'Danish Krone', country: 'dk', countryName: 'Denmark' },
  { code: 'PLN', name: 'Polish Zloty', country: 'pl', countryName: 'Poland' },
  { code: 'ILS', name: 'Israeli New Shekel', country: 'il', countryName: 'Israel' },
  { code: 'PKR', name: 'Pakistani Rupee', country: 'pk', countryName: 'Pakistan' },
  { code: 'BDT', name: 'Bangladeshi Taka', country: 'bd', countryName: 'Bangladesh' },
  { code: 'AFN', name: 'Afghan Afghani', country: 'af', countryName: 'Afghanistan' },
  { code: 'ALL', name: 'Albanian Lek', country: 'al', countryName: 'Albania' },
  { code: 'AMD', name: 'Armenian Dram', country: 'am', countryName: 'Armenia' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', country: 'cw', countryName: 'Curacao' },
  { code: 'AOA', name: 'Angolan Kwanza', country: 'ao', countryName: 'Angola' },
  { code: 'AWG', name: 'Aruban Florin', country: 'aw', countryName: 'Aruba' },
  { code: 'AZN', name: 'Azerbaijani Manat', country: 'az', countryName: 'Azerbaijan' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', country: 'ba', countryName: 'Bosnia and Herzegovina' },
  { code: 'BBD', name: 'Barbadian Dollar', country: 'bb', countryName: 'Barbados' },
  { code: 'BHD', name: 'Bahraini Dinar', country: 'bh', countryName: 'Bahrain' },
  { code: 'BIF', name: 'Burundian Franc', country: 'bi', countryName: 'Burundi' },
  { code: 'BMD', name: 'Bermudan Dollar', country: 'bm', countryName: 'Bermuda' },
  { code: 'BND', name: 'Brunei Dollar', country: 'bn', countryName: 'Brunei' },
  { code: 'BOB', name: 'Bolivian Boliviano', country: 'bo', countryName: 'Bolivia' },
  { code: 'BSD', name: 'Bahamian Dollar', country: 'bs', countryName: 'Bahamas' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', country: 'bt', countryName: 'Bhutan' },
  { code: 'BWP', name: 'Botswanan Pula', country: 'bw', countryName: 'Botswana' },
  { code: 'BYN', name: 'Belarusian Ruble', country: 'by', countryName: 'Belarus' },
  { code: 'BZD', name: 'Belize Dollar', country: 'bz', countryName: 'Belize' },
  { code: 'CDF', name: 'Congolese Franc', country: 'cd', countryName: 'Democratic Republic of the Congo' },
  { code: 'CRC', name: 'Costa Rican Colón', country: 'cr', countryName: 'Costa Rica' },
  { code: 'CUP', name: 'Cuban Peso', country: 'cu', countryName: 'Cuba' },
  { code: 'CVE', name: 'Cape Verdean Escudo', country: 'cv', countryName: 'Cape Verde' },
  { code: 'CZK', name: 'Czech Koruna', country: 'cz', countryName: 'Czech Republic' },
  { code: 'DJF', name: 'Djiboutian Franc', country: 'dj', countryName: 'Djibouti' },
  { code: 'DOP', name: 'Dominican Peso', country: 'do', countryName: 'Dominican Republic' },
  { code: 'DZD', name: 'Algerian Dinar', country: 'dz', countryName: 'Algeria' },
  { code: 'ERN', name: 'Eritrean Nakfa', country: 'er', countryName: 'Eritrea' },
  { code: 'ETB', name: 'Ethiopian Birr', country: 'et', countryName: 'Ethiopia' },
  { code: 'FJD', name: 'Fijian Dollar', country: 'fj', countryName: 'Fiji' },
  { code: 'FKP', name: 'Falkland Islands Pound', country: 'fk', countryName: 'Falkland Islands' },
  { code: 'GEL', name: 'Georgian Lari', country: 'ge', countryName: 'Georgia' },
  { code: 'GHS', name: 'Ghanaian Cedi', country: 'gh', countryName: 'Ghana' },
  { code: 'GIP', name: 'Gibraltar Pound', country: 'gi', countryName: 'Gibraltar' },
  { code: 'GMD', name: 'Gambian Dalasi', country: 'gm', countryName: 'Gambia' },
  { code: 'GNF', name: 'Guinean Franc', country: 'gn', countryName: 'Guinea' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', country: 'gt', countryName: 'Guatemala' },
  { code: 'GYD', name: 'Guyanaese Dollar', country: 'gy', countryName: 'Guyana' },
  { code: 'HNL', name: 'Honduran Lempira', country: 'hn', countryName: 'Honduras' },
  { code: 'HRK', name: 'Croatian Kuna', country: 'hr', countryName: 'Croatia' },
  { code: 'HTG', name: 'Haitian Gourde', country: 'ht', countryName: 'Haiti' },
  { code: 'HUF', name: 'Hungarian Forint', country: 'hu', countryName: 'Hungary' },
  { code: 'IQD', name: 'Iraqi Dinar', country: 'iq', countryName: 'Iraq' },
  { code: 'IRR', name: 'Iranian Rial', country: 'ir', countryName: 'Iran' },
  { code: 'ISK', name: 'Icelandic Króna', country: 'is', countryName: 'Iceland' },
  { code: 'JMD', name: 'Jamaican Dollar', country: 'jm', countryName: 'Jamaica' },
  { code: 'JOD', name: 'Jordanian Dinar', country: 'jo', countryName: 'Jordan' },
  { code: 'KGS', name: 'Kyrgystani Som', country: 'kg', countryName: 'Kyrgyzstan' },
  { code: 'KHR', name: 'Cambodian Riel', country: 'kh', countryName: 'Cambodia' },
  { code: 'KMF', name: 'Comorian Franc', country: 'km', countryName: 'Comoros' },
  { code: 'KWD', name: 'Kuwaiti Dinar', country: 'kw', countryName: 'Kuwait' },
  { code: 'KYD', name: 'Cayman Islands Dollar', country: 'ky', countryName: 'Cayman Islands' },
  { code: 'KZT', name: 'Kazakhstani Tenge', country: 'kz', countryName: 'Kazakhstan' },
  { code: 'LAK', name: 'Laotian Kip', country: 'la', countryName: 'Laos' },
  { code: 'LBP', name: 'Lebanese Pound', country: 'lb', countryName: 'Lebanon' },
  { code: 'LKR', name: 'Sri Lankan Rupee', country: 'lk', countryName: 'Sri Lanka' },
  { code: 'LRD', name: 'Liberian Dollar', country: 'lr', countryName: 'Liberia' },
  { code: 'LSL', name: 'Lesotho Loti', country: 'ls', countryName: 'Lesotho' },
  { code: 'LYD', name: 'Libyan Dinar', country: 'ly', countryName: 'Libya' },
  { code: 'MAD', name: 'Moroccan Dirham', country: 'ma', countryName: 'Morocco' },
  { code: 'MDL', name: 'Moldovan Leu', country: 'md', countryName: 'Moldova' },
  { code: 'MGA', name: 'Malagasy Ariary', country: 'mg', countryName: 'Madagascar' },
  { code: 'MKD', name: 'Macedonian Denar', country: 'mk', countryName: 'Macedonia' },
  { code: 'MMK', name: 'Myanmar Kyat', country: 'mm', countryName: 'Myanmar' },
  { code: 'MNT', name: 'Mongolian Tugrik', country: 'mn', countryName: 'Mongolia' },
  { code: 'MOP', name: 'Macanese Pataca', country: 'mo', countryName: 'Macau' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', country: 'mr', countryName: 'Mauritania' },
  { code: 'MUR', name: 'Mauritian Rupee', country: 'mu', countryName: 'Mauritius' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', country: 'mv', countryName: 'Maldives, Maldive' },
  { code: 'MWK', name: 'Malawian Kwacha', country: 'mw', countryName: 'Malawi' },
  { code: 'MZN', name: 'Mozambican Metical', country: 'mz', countryName: 'Mozambique' },
  { code: 'NAD', name: 'Namibian Dollar', country: 'na', countryName: 'Namibia' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', country: 'ni', countryName: 'Nicaragua' },
  { code: 'NPR', name: 'Nepalese Rupee', country: 'np', countryName: 'Nepal' },
  { code: 'OMR', name: 'Omani Rial', country: 'om', countryName: 'Oman' },
  { code: 'PAB', name: 'Panamanian Balboa', country: 'pa', countryName: 'Panama' },
  { code: 'PGK', name: 'Papua New Guinean Kina', country: 'pg', countryName: 'Papua New Guinea' },
  { code: 'PYG', name: 'Paraguayan Guarani', country: 'py', countryName: 'Paraguay' },
  { code: 'QAR', name: 'Qatari Rial', country: 'qa', countryName: 'Qatar' },
  { code: 'RON', name: 'Romanian Leu', country: 'ro', countryName: 'Romania' },
  { code: 'RSD', name: 'Serbian Dinar', country: 'rs', countryName: 'Serbia' },
  { code: 'RWF', name: 'Rwanda Franc', country: 'rw', countryName: 'Rwanda' },
  { code: 'SBD', name: 'Solomon Islands Dollar', country: 'sb', countryName: 'Solomon Islands' },
  { code: 'SCR', name: 'Seychellois Rupee', country: 'sc', countryName: 'Seychelles' },
  { code: 'SDG', name: 'Sudanese Pound', country: 'sd', countryName: 'Sudan' },
  { code: 'SHP', name: 'St. Helena Pound', country: 'sh', countryName: 'Saint Helena' },
  { code: 'SLL', name: 'Sierra Leonean Leone', country: 'sl', countryName: 'Sierra Leone' },
  { code: 'SOS', name: 'Somali Shilling', country: 'so', countryName: 'Somalia' },
  { code: 'SRD', name: 'Surinamese Dollar', country: 'sr', countryName: 'Suriname' },
  { code: 'SSP', name: 'South Sudanese Pound', country: 'ss', countryName: 'South Sudan' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', country: 'st', countryName: 'Sao Tome and Principe' },
  { code: 'SYP', name: 'Syrian Pound', country: 'sy', countryName: 'Syria' },
  { code: 'SZL', name: 'Swazi Lilangeni', country: 'sz', countryName: 'Swaziland' },
  { code: 'TJS', name: 'Tajikistani Somoni', country: 'tj', countryName: 'Tajikistan' },
  { code: 'TMT', name: 'Turkmenistani Manat', country: 'tm', countryName: 'Turkmenistan' },
  { code: 'TND', name: 'Tunisian Dinar', country: 'tn', countryName: 'Tunisia' },
  { code: 'TOP', name: 'Tongan Paʻanga', country: 'to', countryName: 'Tonga' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', country: 'tt', countryName: 'Trinidad and Tobago' },
  { code: 'TWD', name: 'New Taiwan Dollar', country: 'tw', countryName: 'Taiwan' },
  { code: 'TZS', name: 'Tanzanian Shilling', country: 'tz', countryName: 'Tanzania' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', country: 'ua', countryName: 'Ukraine' },
  { code: 'UGX', name: 'Ugandan Shilling', country: 'ug', countryName: 'Uganda' },
  { code: 'UYU', name: 'Uruguayan Peso', country: 'uy', countryName: 'Uruguay' },
  { code: 'UZS', name: 'Uzbekistani Som', country: 'uz', countryName: 'Uzbekistan' },
  { code: 'VES', name: 'Venezuelan Bolívar Soberano', country: 've', countryName: 'Venezuela' },
  { code: 'VUV', name: 'Vanuatu Vatu', country: 'vu', countryName: 'Vanuatu' },
  { code: 'WST', name: 'Samoan Tala', country: 'ws', countryName: 'Samoa' },
  { code: 'XAF', name: 'Central African CFA Franc', country: 'cm', countryName: 'Cameroon' },
  { code: 'XCD', name: 'East Caribbean Dollar', country: 'ag', countryName: 'Antigua and Barbuda' },
  { code: 'XOF', name: 'West African CFA Franc', country: 'sn', countryName: 'Senegal' },
  { code: 'XPF', name: 'CFP Franc', country: 'pf', countryName: 'French Polynesia' },
  { code: 'YER', name: 'Yemeni Rial', country: 'ye', countryName: 'Yemen' },
  { code: 'ZMW', name: 'Zambian Kwacha', country: 'zm', countryName: 'Zambia' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', country: 'zw', countryName: 'Zimbabwe' },
];

export const getFlagUrl = (countryCode) => {
  return `https://flagcdn.com/w40/${countryCode.toLowerCase()}.png`;
};
